# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phi_app <- function(X_stand, anc, tau) {
    .Call(`_TobitBART_phi_app`, X_stand, anc, tau)
}

